### PR TITLE
Final Pull Into Master

### PR DESCRIPTION
**Pull request by craig95**

### CODE REVIEW

**Review by vossca — APPROVED** [review]

**Review by keyboardninja96 — APPROVED** [review]
Everything looks good, thanks

**Review by PeteElite — APPROVED** [review]
Everything looks good.

**Review by Seonin — CHANGES_REQUESTED** [review]
Everything looks great all diagrams are where they should be and it is presented very well

**Review by Seonin — APPROVED** [review]

**Review by banzodude — APPROVED** [review]
looks fine to me

**Pull request merged**
