### PR TITLE
POI Branch

### PR DESCRIPTION
**Pull request by keyboardninja96**
I did the External Interface Requirements and Performance Requirements including the diagrams, they're up for review. I didn't add Kea's "Software System Attributes" section to the POI.tex file, or should I add it?

### CODE REVIEW

**Review by craig95 — CHANGES_REQUESTED** [review]
Kea first needs to add her stuff before we can merge the POI branch.

Please also remove everything before \section{External Interface Requirements} as this is done in the main.tex file
Also remove the \end{document} for the same reason.

**Review by vossca — DISMISSED** [review]
Remember to keep the diagrams in the order given to us in the specifications pdf

**Review by Seonin — DISMISSED** [review]
Please add design patterns to your class diagram

**Review by craig95 — APPROVED** [review]
All needed sections have been added/updated.

**Pull request merged**
